// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: protobufapi.proto

package protobufapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command消息包含两个字段，一个用于维护操作系统的命令；一个用于维护命令执行的输出
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            string                 `protobuf:"bytes,1,opt,name=In,proto3" json:"In,omitempty"`
	Out           string                 `protobuf:"bytes,2,opt,name=Out,proto3" json:"Out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_protobufapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_protobufapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_protobufapi_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Command) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

type SleepTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int32                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepTime) Reset() {
	*x = SleepTime{}
	mi := &file_protobufapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepTime) ProtoMessage() {}

func (x *SleepTime) ProtoReflect() protoreflect.Message {
	mi := &file_protobufapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepTime.ProtoReflect.Descriptor instead.
func (*SleepTime) Descriptor() ([]byte, []int) {
	return file_protobufapi_proto_rawDescGZIP(), []int{1}
}

func (x *SleepTime) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// Empty 用来代替null的空消息 定义这个Empty类型是由于gRPC不显式地允许空值
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protobufapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobufapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobufapi_proto_rawDescGZIP(), []int{2}
}

var File_protobufapi_proto protoreflect.FileDescriptor

const file_protobufapi_proto_rawDesc = "" +
	"\n" +
	"\x11protobufapi.proto\x12\vprotobufapi\"+\n" +
	"\aCommand\x12\x0e\n" +
	"\x02In\x18\x01 \x01(\tR\x02In\x12\x10\n" +
	"\x03Out\x18\x02 \x01(\tR\x03Out\"\x1f\n" +
	"\tSleepTime\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x05R\x04time\"\a\n" +
	"\x05Empty2\xb7\x01\n" +
	"\aImplant\x128\n" +
	"\fFetchCommand\x12\x12.protobufapi.Empty\x1a\x14.protobufapi.Command\x126\n" +
	"\n" +
	"SendOutput\x12\x14.protobufapi.Command\x1a\x12.protobufapi.Empty\x12:\n" +
	"\fGetSleepTime\x12\x12.protobufapi.Empty\x1a\x16.protobufapi.SleepTime2~\n" +
	"\x06Client\x128\n" +
	"\n" +
	"RunCommand\x12\x14.protobufapi.Command\x1a\x14.protobufapi.Command\x12:\n" +
	"\fSetSleepTime\x12\x16.protobufapi.SleepTime\x1a\x12.protobufapi.EmptyB\x0fZ\r./protobufapib\x06proto3"

var (
	file_protobufapi_proto_rawDescOnce sync.Once
	file_protobufapi_proto_rawDescData []byte
)

func file_protobufapi_proto_rawDescGZIP() []byte {
	file_protobufapi_proto_rawDescOnce.Do(func() {
		file_protobufapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufapi_proto_rawDesc), len(file_protobufapi_proto_rawDesc)))
	})
	return file_protobufapi_proto_rawDescData
}

var file_protobufapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobufapi_proto_goTypes = []any{
	(*Command)(nil),   // 0: protobufapi.Command
	(*SleepTime)(nil), // 1: protobufapi.SleepTime
	(*Empty)(nil),     // 2: protobufapi.Empty
}
var file_protobufapi_proto_depIdxs = []int32{
	2, // 0: protobufapi.Implant.FetchCommand:input_type -> protobufapi.Empty
	0, // 1: protobufapi.Implant.SendOutput:input_type -> protobufapi.Command
	2, // 2: protobufapi.Implant.GetSleepTime:input_type -> protobufapi.Empty
	0, // 3: protobufapi.Client.RunCommand:input_type -> protobufapi.Command
	1, // 4: protobufapi.Client.SetSleepTime:input_type -> protobufapi.SleepTime
	0, // 5: protobufapi.Implant.FetchCommand:output_type -> protobufapi.Command
	2, // 6: protobufapi.Implant.SendOutput:output_type -> protobufapi.Empty
	1, // 7: protobufapi.Implant.GetSleepTime:output_type -> protobufapi.SleepTime
	0, // 8: protobufapi.Client.RunCommand:output_type -> protobufapi.Command
	2, // 9: protobufapi.Client.SetSleepTime:output_type -> protobufapi.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufapi_proto_init() }
func file_protobufapi_proto_init() {
	if File_protobufapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufapi_proto_rawDesc), len(file_protobufapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobufapi_proto_goTypes,
		DependencyIndexes: file_protobufapi_proto_depIdxs,
		MessageInfos:      file_protobufapi_proto_msgTypes,
	}.Build()
	File_protobufapi_proto = out.File
	file_protobufapi_proto_goTypes = nil
	file_protobufapi_proto_depIdxs = nil
}
