// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: protobufapi/greeter.proto

package protobufapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protobufapi_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobufapi_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobufapi_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_protobufapi_greeter_proto protoreflect.FileDescriptor

const file_protobufapi_greeter_proto_rawDesc = "" +
	"\n" +
	"\x19protobufapi/greeter.proto\x12\vprotobufapi\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body2y\n" +
	"\vChatService\x126\n" +
	"\bSayHello\x12\x14.protobufapi.Message\x1a\x14.protobufapi.Message\x122\n" +
	"\x04Test\x12\x14.protobufapi.Message\x1a\x14.protobufapi.MessageB\x1cZ\x1aZ1/protobufapi;protobufapib\x06proto3"

var (
	file_protobufapi_greeter_proto_rawDescOnce sync.Once
	file_protobufapi_greeter_proto_rawDescData []byte
)

func file_protobufapi_greeter_proto_rawDescGZIP() []byte {
	file_protobufapi_greeter_proto_rawDescOnce.Do(func() {
		file_protobufapi_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufapi_greeter_proto_rawDesc), len(file_protobufapi_greeter_proto_rawDesc)))
	})
	return file_protobufapi_greeter_proto_rawDescData
}

var file_protobufapi_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobufapi_greeter_proto_goTypes = []any{
	(*Message)(nil), // 0: protobufapi.Message
}
var file_protobufapi_greeter_proto_depIdxs = []int32{
	0, // 0: protobufapi.ChatService.SayHello:input_type -> protobufapi.Message
	0, // 1: protobufapi.ChatService.Test:input_type -> protobufapi.Message
	0, // 2: protobufapi.ChatService.SayHello:output_type -> protobufapi.Message
	0, // 3: protobufapi.ChatService.Test:output_type -> protobufapi.Message
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufapi_greeter_proto_init() }
func file_protobufapi_greeter_proto_init() {
	if File_protobufapi_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufapi_greeter_proto_rawDesc), len(file_protobufapi_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufapi_greeter_proto_goTypes,
		DependencyIndexes: file_protobufapi_greeter_proto_depIdxs,
		MessageInfos:      file_protobufapi_greeter_proto_msgTypes,
	}.Build()
	File_protobufapi_greeter_proto = out.File
	file_protobufapi_greeter_proto_goTypes = nil
	file_protobufapi_greeter_proto_depIdxs = nil
}
